version: "3.7"

services:
    sistema_financeiro:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sistema-financeiro-network
    # nginx
    nginx:
        container_name: servidor-nginx
        image: nginx:alpine
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - sistema-financeiro-network
     # db mysql ${DB_DATABASE} //Busca do arquivo .env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8899:80
        networks:
            - sistema-financeiro-network

networks:
    sistema-financeiro-network:
        driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8899/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8989/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root

