version: "3.7"

services:
    sistema_gestao_financeira:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sistema-gestao-financeira
    # nginx
    nginx:
        container_name: servidor-nginx
        image: nginx:alpine
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - sistema-gestao-financeira
     # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
        container_name: banco-mysql
        platform: linux/x86_64
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - sistema-gestao-financeira

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8899:80
        networks:
            - sistema-gestao-financeira

networks:
    sistema-gestao-financeira:
        driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8899/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8989/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root

